@host = http://localhost:3080

# @name clipList
GET {{host}}/clips

####
# @name videoList
GET {{host}}/videos

####
# @name getVideoInfo
GET {{host}}/videos/{{videoID}}/info

####
# @name putClip
@videoID = {{videoList.response.body.$[0].id}}

PUT {{host}}/clips
Content-Type: application/json

{
  "videoID": "{{videoID}}",
  "start":4.5,
  "length":3,
  "options":{}
}

####
# @name getClipInfo
@clipID = {{clipList.response.body.$[0].id}}
@filename = {{clipList.response.body.$[0].filename}}
GET {{host}}/clips/{{clipID}}

####
# @name deleteClip
DELETE {{host}}/clips/{{clipID}}

####
# @name postFrameCache
POST {{host}}/frames/{{videoID}}

####
# @name deleteFrameCache
DELETE {{host}}/frames/{{videoID}}

####
# @name postClipCache
POST {{host}}/clipcache/{{videoID}}

####
# @name deleteClipCache
DELETE {{host}}/clipcache/{{videoID}}

####
# @name getClipFile
# Note: should come from public/static server
GET {{host}}/clips/{{filename}}

####
# @name getFrame
GET {{host}}/frames/{{videoID}}/0

####
# @name getFrame2
GET {{host}}/frames/{{videoID}}/0:1

####
# @name getFrame3
GET {{host}}/frames/{{videoID}}/0:2

