@host = http://localhost:3080

# @name gifList
GET {{host}}/gif
####
# @name videoList
GET {{host}}/video
####
# @name putGIF
@videoID = {{videoList.response.body.$[0].videoID}}

PUT {{host}}/gif
Content-Type: application/json

{
  "videoID": "{{videoID}}",
  "start":4.5,
  "length":3,
  "options":{}
}
####
@gifID = {{gifList.response.body.$[0].gifID}}
@filename = {{gifList.response.body.$[0].filename}}
GET {{host}}/gif/{{gifID}}
####
DELETE {{host}}/gif/{{gifID}}
####
POST {{host}}/framecache/{{videoID}}

####
DELETE {{host}}/framecache/{{videoID}}

####
# Public
GET {{host}}/gifs/{{filename}}

####
GET {{host}}/frameCache/{{videoID}}/0
