@host = http://localhost:3080

# @name videoList
GET {{host}}/videos
####
# @name rootAppStaticHTML
GET {{host}}/
####
@videoID = {{videoList.response.body.$[0].id}}
@videoFilename = {{videoList.response.body.$[0].filename}}
GET {{host}}/videos/{{videoID}}
####
GET {{host}}/videos/downloads/progress
####
POST {{host}}/videos/downloads
Content-Type: application/json

{"url": "https://www.youtube.com/watch?v=MMXAjhAopyg"}
####
DELETE {{host}}/videos/{{videoID}}

####
GET {{host}}/videos/{{videoID}}/info

####
# Public
# GET {{host}}/videos/{{videoFilename}}

####
POST {{host}}/videos/info
Content-Type: application/json

{"url": "https://www.youtube.com/watch?v=MMXAjhAopyg"}
