@host = http://localhost:3080

# @name videoList
GET {{host}}/video
####
@videoID = {{videoList.response.body.$[0].videoID}}
@thumbnailFile = {{videoList.response.body.$[0].thumbnailFile}}
GET {{host}}/video/{{videoID}}
####
GET {{host}}/video/download/progress
####
POST {{host}}/video/download
Content-Type: application/json

{"url": "https://www.youtube.com/watch?v=MMXAjhAopyg"}
####
DELETE {{host}}/video/{{videoID}}

####
GET {{host}}/videoInfo/{{videoID}}

####
# Public
GET {{host}}/thumbnails/{{thumbnailFile}}
